//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockageDecisionsAgissantPPDS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>GS1 Gouvernance - reporting</string>
  <string>GS2 Help desk</string>
  <string>GS3 Support proximité</string>
  <string>GS4 Appro-distribution</string>
  <string>GS5 IQ Matériels</string>
  <string>GS6-a Infras</string>
  <string>GS6-b Outils</string>
  <string>GS6-c Moy impression</string>
  <string>GS7 Maintenance hardware</string>
  <string>GS8 IQ Souches applis</string>
  <string>GS9-a Télédiffusion</string>
  <string>GS9-b Admin outils</string>
  <string>Gestion des actifs</string>
  <string>Gestion des changements</string>
  <string>Gestion des crises</string>
  <string>Gestion des problèmes</string>
  <string>Gestion des incidents</string>
  <string>Pilotage ST</string>
  <string>Management PPDS</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Persister_Domaines_List {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Persister_Domaines_List"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RSS")]
        public string Persister_Type {
            get {
                return ((string)(this["Persister_Type"]));
            }
            set {
                this["Persister_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Persister_Csv_Path {
            get {
                return ((string)(this["Persister_Csv_Path"]));
            }
            set {
                this["Persister_Csv_Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Persister_RSS_Uri {
            get {
                return ((string)(this["Persister_RSS_Uri"]));
            }
            set {
                this["Persister_RSS_Uri"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>RSS</string>\r\n  <string>Csv</string>\r\n  <string>Memory</string>\r\n</ArrayOf" +
            "String>")]
        public global::System.Collections.Specialized.StringCollection Persister_Type_Values {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Persister_Type_Values"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>RSS</string>\r\n  <string>List</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Persister_Domaines_Source_Values {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Persister_Domaines_Source_Values"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RSS")]
        public string Persister_Domaines_Source {
            get {
                return ((string)(this["Persister_Domaines_Source"]));
            }
            set {
                this["Persister_Domaines_Source"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public char Separator {
            get {
                return ((char)(this["Separator"]));
            }
            set {
                this["Separator"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SettingsEnabled {
            get {
                return ((bool)(this["SettingsEnabled"]));
            }
        }
    }
}
